### ISSUE TITLE
Error: Answered with error to command 0xc4: The vehicle 'ego_1' to add already exists.

### ISSUE THREAD

**Issue by paller123** [011235813/cm3#2]
Hello~When i execute python "train_offpolicy.py --env ../env_sumo/simple/merge.sumocfg", Prompting error:Answered with error to command 0xc4: The vehicle 'ego_1' to add already exists.What does it mean?
Hope to get a reply.Thanks~

**Comment by paller123** [comment]
When i execute python "train_offpolicy.py --env ../env_sumo/simple/merge.sumocfg", Prompting error:Answered with error to command 0xc4: The vehicle 'ego_1' to add already exists.What does it mean?
Hope to get a reply.Thanks

**Comment by lxqever** [comment]
请问下，怎么解决的？

**Comment by lxqever** [comment]
> When i execute python "train_offpolicy.py --env ../env_sumo/simple/merge.sumocfg", Prompting error:Answered with error to command 0xc4: The vehicle 'ego_1' to add already exists.What does it mean? Hope to get a reply.Thanks

请问下，怎么解决的？
